version: '3.8'

services:
    web:
        image: eventure:latest
        build:
            target: web
            context: .
        env_file:
            - .env
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db

