name: Laravel CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Login to Docker Registry
    - name: Login to Docker Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ vars.DOCKER_REGISTRY_LOCATION }}
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASS }}

    - name: Creating env
      run: |
        cp .env.testing .env
        echo DB_HOST = ${{ vars.DB_HOST }} >> .env
        echo DB_DATABASE = ${{ secrets.DB_DATABASE }} >> .env
        echo DB_USERNAME = ${{ secrets.DB_USERNAME }} >> .env
        echo DB_PASSWORD = ${{ secrets.DB_PASSWORD }} >> .env

        cat .env

    # Build and Push Docker Image
    - name: Build and Push Docker Image
      run: |
        npm run image
        docker push ${{ vars.DOCKER_REGISTRY_LOCATION }}/eventure-php-fpm:latest

    # Deploy to VPS via SSH
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ vars.VPS_IP }}
        username: ${{ vars.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Navigate to project directory
          cd ~/eventure-docker-laravel

          # Pull the latest image
          docker pull ${{ vars.DOCKER_REGISTRY_LOCATION }}/eventure-php-fpm:latest

          # Stop existing containers
          docker compose down

          # Pull from github
          git pull origin main

          # Start new containers
          docker compose up -d

          # Run migrations
          docker compose exec -T app php artisan migrate --force

          # Clear config cache
          # docker compose exec -T app php artisan config:clear
          # docker compose exec -T app php artisan config:cache
